### ISSUE TITLE
Convert markdown from GitHub to Slack format

### ISSUE THREAD

**Issue by eXConf** [halalbooking/sbot#1]
Some markdown elements that are present in GitHub issues don't exist or have different syntax in Slack threads. Thus we need to convert them into something Slack can show in a nice way.

### Elements that are well formatted as is:

- italic text (with `_ _` syntax)
- quoted text
- single line of code
- multiline code (with \`\`\` \`\`\` syntax)
- ordered list

### Elements that require conversion in SBot:

- headers 1-6: should be converted to bold text as there are no headers in Slack's markdown
- bold text: should be converted from `**text**` to `*text*`
- unordered lists: items should be converted from `- item` to `• item`
- linked text: should be converted from `[Link text](https://link.address)` to `<https://link.address|Link text>`
- multiline code (with four spaces at the start of a line): should be converted to \`\`\` \`\`\` syntax
- italic text (with `* *` syntax): should be converted to `_ _` syntax

**Comment by rustamli** [comment]
Thanks for looking into this @eXConf

**Comment by eXConf** [comment]
Original issue was updated with two more problematic cases:
- multiline code (with four spaces at the start of a line): should be converted to \`\`\` \`\`\` syntax
- italic text (with `* *` syntax): should be converted to `_ _` syntax
